name: Run Codeception Tests and Generate Allure Report

on:
  push:
    branches:
      - main   # Ejecutar en la rama principal
  pull_request:
    branches:
      - main   # Ejecutar cuando haya un pull request hacia la rama principal

jobs:
  run_tests:
    runs-on: ubuntu-latest  # Puedes usar un runner de Ubuntu

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'  # Ajusta la versión de PHP según sea necesario 

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip
          curl -sS https://getcomposer.org/installer | php
          mv composer.phar /usr/local/bin/composer
          cd project  # Cambia al directorio del proyecto
          composer install --dev  # Instalar las dependencias del proyecto

      - name: Install Codeception and Allure Codeception module
        run: |
          cd project  # Cambia al directorio del proyecto
          composer require --dev codeception/codeception
          composer require allure-framework/allure-codeception

      - name: Install Allure CLI
        run: |
          wget -q https://github.com/allure-framework/allure2/releases/download/2.18.1/allure-2.18.1.tgz
          tar -zxvf allure-2.18.1.tgz
          sudo mv allure-2.18.1 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/local/bin/allure

      - name: Give execute permissions to Codeception
        run: |
          cd project  # Cambia al directorio del proyecto
          chmod +x vendor/bin/codecept  # Otorga permisos de ejecución a Codeception
      - name: Check Codeception and Allure installation
        run: |
          cd project
          composer validate
          composer info codeception/codeception
          composer info allure-framework/allure-codeception
          vendor/bin/codecept --version
      - name: Build Codeception
        run: |
          cd project  # Cambia al directorio del proyecto
          vendor/bin/codecept build  # Prepara el entorno de pruebas

      - name: Run Tests
        run: |
          cd project  # Cambia al directorio del proyecto
          vendor/bin/codecept run --debug --ext "Qameta\Allure\Codeception\AllureCodeception"

      - name: Generate Allure Report
        run: |
          cd project  # Cambia al directorio del proyecto
          allure generate tests/_output/allure-results -o ./project/bbd --clean  # Genera el reporte de Allure
