name: Combined Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  phpunit-and-mutation-tests:
    runs-on: ubuntu-latest

    steps:
    # Clona el código del repositorio
    - name: Checkout code
      uses: actions/checkout@v3

    # Configura PHP
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: xdebug # Necesario para la cobertura de código

    # Instala las dependencias de Composer
    - name: Install dependencies
      run: |
        cd project
        composer install

    # Corrige permisos para vendor/bin/phpunit
    - name: Fix permissions for PHPUnit
      run: |
        cd project
        chmod +x vendor/bin/phpunit

    # Ejecuta PHPUnit y genera el informe HTML de cobertura directamente en la carpeta especificada
    - name: Run PHPUnit tests
      run: |
        cd project
        php vendor/bin/phpunit --coverage-html informes/pruebasunitarias

    # Genera la cobertura de código en formato XML para Infection
    - name: Generate PHPUnit coverage (XML)
      run: |
        cd project
        php vendor/bin/phpunit --coverage-xml=coverage

    # Genera el informe HTML de Infection
    - name: Generate infection HTML report
      run: |
        cd project
        php vendor/bin/infection --coverage=coverage --logger-html=informes/mutacion/infection-log.html

    # Genera el resumen de mutaciones en formato de progreso
    - name: Generate infection summary
      run: |
        cd project
        php vendor/bin/infection --coverage=coverage --formatter=progress > informes/mutacion/infection-summary.txt


    # Realiza commit y push de los informes generados al repositorio
    - name: Commit and push reports to repository
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add project/informes/pruebasunitarias project/informes/mutacion/infection-summary.txt project/informes/mutacion/infection-log.html
        git commit -m "Add PHPUnit and Mutation test reports"
        git push origin main
        
    # Sube los informes como artefactos
    - name: Upload test reports as artifacts
      uses: actions/upload-artifact@v3
      with:
        name: combined-test-reports
        path: |
          project/informes/pruebasunitarias/
          project/informes/mutacion/infection-summary.txt
          project/informes/mutacion/infection-log.html
