name: Snyk Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  snyk-analysis:
    name: Run Snyk Analysis
    runs-on: ubuntu-latest

    steps:
      # Checkout del código
      - name: Checkout repository
        uses: actions/checkout@v3

      # Configurar PHP 8.2
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      # Instalar dependencias (Composer)
      - name: Install dependencies
        run: |
          cd project  # Cambiar a la carpeta del proyecto
          composer install

      # Instalar Snyk CLI
      - name: Install Snyk CLI
        run: npm install -g snyk

      # Autenticarse en Snyk
      - name: Authenticate with Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      # Ejecutar pruebas de Snyk y generar el reporte JSON
      - name: Run Snyk Code test
        run: |
          snyk code test --sarif-file-output=project/informes/snyk/snyk.sarif --json-file-output=project/informes/snyk/snyk-report.json || echo "Snyk code test completed with issues"
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # Verificar que el archivo SARIF se generó correctamente
      - name: Check SARIF file existence
        run: ls -la project/informes/snyk/snyk.sarif

      # Instalar Snyk-to-HTML y generar el reporte HTML
      - name: Generate HTML report from SARIF
        run: |
          npm install -g snyk-to-html
          snyk-to-html -i project/informes/snyk/snyk.sarif -o project/informes/snyk/snyk-report.html

      # Verificar que el reporte HTML se generó correctamente
      - name: Check HTML report existence
        run: ls -la project/informes/snyk/snyk-report.html

      # Subir el archivo SARIF a GitHub Code Scanning
      - name: Upload Snyk SARIF result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: project/informes/snyk/snyk.sarif  # Subir el archivo SARIF generado

      # Commit y push de los informes al repositorio principal (rama main)
      - name: Push Snyk reports to main branch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add project/informes/snyk/*
          git commit -m "Add Snyk reports" || echo "No changes to commit"
          git push origin main
