name: SonarQube Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarcloud:
    name: Run SonarCloud Analysis
    runs-on: ubuntu-latest

    steps:
      # Checkout del código
      - name: Checkout repository
        uses: actions/checkout@v3

      # Configurar PHP 8.2
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      # Instalar dependencias (si usas Composer)
      - name: Install dependencies
        run: |
          cd project  # Cambiar a la carpeta del proyecto
          composer install


      # Ejecutar el análisis de SonarCloud utilizando el archivo 'sonar-project.properties'
      - name: Run SonarCloud Analysis
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          projectBaseDir: project  # Ruta al directorio base donde está el archivo 'sonar-project.properties'
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # Usa el token almacenado en los secretos
