name: Mutation Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  mutation-tests:
    runs-on: ubuntu-latest

    steps:
    # Clona el código del repositorio
    - name: Checkout code
      uses: actions/checkout@v3

    # Configura PHP
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: xdebug # Necesario para la cobertura de código

    # Instala las dependencias de Composer
    - name: Install dependencies
      run: |
        cd project
        composer install

    # Crea los directorios de informes si no existen
    - name: Create directories for reports
      run: |
        mkdir -p project/informes/mutacion

    # Corrige permisos para el directorio de informes
    - name: Fix permissions for mutation report directory
      run: |
        chmod -R 777 project/informes/mutacion

    # Genera la cobertura de código en formato XML
    - name: Generate PHPUnit coverage (XML)
      run: |
        cd project
        php vendor/bin/phpunit --coverage-xml=coverage

    # Genera el informe HTML de Infection
    - name: Generate infection HTML report
      run: |
        cd project
        php vendor/bin/infection --coverage=coverage --logger-html=informes/mutacion/infection-log.html

    # Genera el resumen de mutaciones en formato de progreso
    - name: Generate infection summary
      run: |
        cd project
        php vendor/bin/infection --coverage=coverage --formatter=progress > informes/mutacion/infection-summary.txt

    # Realiza commit y push de los informes generados al repositorio
    - name: Commit and push mutation reports to repository
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add project/informes/mutacion/infection-summary.txt project/informes/mutacion/infection-log.html
        git commit -m "Add mutation test reports"
        git push origin main

    # Sube los informes de Infection como artefactos
    - name: Upload mutation test reports as artifacts
      uses: actions/upload-artifact@v3
      with:
        name: infection-mutation-reports
        path: |
          project/informes/mutacion/infection-summary.txt
          project/informes/mutacion/infection-log.html
