name: PHPUnit Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  phpunit:
    runs-on: ubuntu-latest

    steps:
    # Clona el código del repositorio
    - name: Checkout code
      uses: actions/checkout@v3

    # Configura PHP
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2' # PHP 8.2 según tu solicitud
        extensions: xdebug # Necesario para la cobertura de código

    # Instala las dependencias de Composer
    - name: Install dependencies
      run: |
        cd project
        composer install

    # Corrige permisos para vendor/bin/phpunit
    - name: Fix permissions for PHPUnit
      run: |
        cd project
        chmod +x vendor/bin/phpunit

    # Ejecuta PHPUnit y genera el informe HTML de cobertura directamente en la carpeta especificada
    - name: Run PHPUnit tests
      run: |
        cd project
        php vendor/bin/phpunit --coverage-html informes/pruebasunitarias

    # (Opcional) Sube el informe como artefacto para descargarlo desde GitHub
    - name: Upload coverage report as artifact
      uses: actions/upload-artifact@v3
      with:
        name: phpunit-coverage-report
        path: project/informes/pruebasunitarias/